name: orion
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  math_expressions: ^2.1.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.10

flutter:

  uses-material-design: true

  assets:
    - assets/splash.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android: true
  ios: true
